OCEAN_COLOR_PATH = r"C:\Users\VHF\Desktop\aeronet\LWN_Level15_All_Points_V3\LWN\LWN15\ALL_POINTS"
AEROSOL_INVERSION_PATH = r"C:\Users\VHF\Desktop\aeronet\INV_Level15_All_Points_V3\INV\LEV15\ALL\ALL_POINTS"
AEROSOL_INVERSION_PHASE_FUNCTION_PATH = r"C:\Users\VHF\Desktop\aeronet\INV_PFN_Level15_All_Points_V3\INV\LEV15\PFN\ALL_POINTS"
NEEDED_SITES_PATH = r"C:\Users\VHF\Desktop\satellite-cross-imagery\aeronet\needed_sites.txt"
SITES_POSITIONS_PATH = r"C:\Users\VHF\Desktop\satellite-cross-imagery\aeronet\sites_positions.csv"